### ISSUE TITLE
Github Action Failure

### ISSUE THREAD

**Issue by konsalex** [octokit/octokit-next.js#76]
Hey not sure if I am opening an issue to the right place:

We use: https://github.com/actions/first-interaction and today suddenly it stopped working with an issue:

```bash
Run actions/first-interaction@v1
  with:
    repo-token: ***
    pr-message: Hey @FallingCeilingS 👋.
  Thank you for contributing to Neo4j Design Language, or Needle 🪡 in short.
  
  Be sure to follow the [contribution](https://github.com/neo4j/neo4j-design/blob/main/CONTRIBUTING.md) guidelines 🙌
  
  
/usr/bin/docker run --name f70630e68b[2](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:2)45c7475994[3](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:3)c00[4](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:4)ab4af8e91_c66cb4 --label 817f70 --workdir /github/workspace --rm -e "INPUT_REPO-TOKEN" -e "INPUT_PR-MESSAGE" -e "INPUT_ISSUE-MESSAGE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/neo4j-design/neo4j-design":"/github/workspace" 817f70:630e68b24[5](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:5)c74759943c004ab4af8e91
internal/modules/cjs/loader.js:121[6](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:6)
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /node_modules/@octokit/graphql/index.js
require() of ES modules is not supported.
require() of /node_modules/@octokit/graphql/index.js from /node_modules/@actions/github/lib/github.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/@octokit/graphql/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1216:13)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:93[7](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:7):14)
    at Module.require (internal/modules/cjs/loader.js:10[8](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:8)[9](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:9):1[9](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:10))
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/node_modules/@actions/github/lib/github.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:[10](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:11))
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:[14](https://github.com/neo4j/neo4j-design/actions/runs/3150161627/jobs/5122781583#step:3:15)) {
  code: 'ERR_REQUIRE_ESM'
}
```

And I suspect that it may have something to do with this repo, as you are publishing to `2.3.0` and the latest is this instead the `5.x.x`: https://cdn.jsdelivr.net/npm/@octokit/graphql@latest/package.json

**Comment by gr2m** [comment]
I'm very sorry for that, the problem has been meanwhile resolved.

**Comment by gr2m** [comment]
See https://github.com/octokit/graphql.js/issues/411 for more details
